version: '3.8'

name: 'fakeflix'

services:
  db:
    image: postgres:15-alpine
    container_name: fakeflix_db
    environment:
      POSTGRES_USER: fakeflix
      POSTGRES_PASSWORD: fakeflix
    ports:
      - '5432:5432'
    volumes:
      - .data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: fakeflix-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    command: redis-server --save 60 1 --loglevel warning

volumes:
  redis-data: