import { DefaultEntity } from '@sharedModule/persistence/typeorm/entity/default.entity';
import { Column, Entity, JoinColumn, OneToOne } from 'typeorm';
import { Video } from './video.entity';

@Entity({ name: 'VideoMetadata' })
export class VideoMetadata extends DefaultEntity<VideoMetadata> {
  @Column({ type: 'text' })
  transcript: string;

  @Column({ type: 'text', nullable: true })
  autoGeneratedDescription: string | null;

  @Column({ type: 'integer', nullable: true })
  ageRating: number | null;

  @Column({ type: 'text', nullable: true })
  ageRatingExplanation: string | null;

  @Column('text', { array: true, nullable: true })
  ageRatingCategories: string[] | null;

  @OneToOne(() => Video, (video) => video.metadata)
  @JoinColumn({
    name: 'video_id',
    referencedColumnName: 'id',
  })
  video: Video;
}
