import { DefaultEntity } from '@sharedModule/persistence/typeorm/entity/default.entity';
import { Column, Entity, JoinColumn, OneToOne, VersionColumn } from 'typeorm';
import { Video } from './video.entity';

@Entity({ name: 'VideoMetadata' })
export class VideoMetadata extends DefaultEntity<VideoMetadata> {
  @Column({ type: 'text' })
  transcript: string;

  @Column({ type: 'text', nullable: true })
  autoGeneratedDescription: string | null;

  @Column({ type: 'integer', nullable: true })
  ageRating: number | null;

  @Column({ type: 'integer' })
  duration: number;

  @Column({ type: 'text', nullable: true })
  ageRatingExplanation: string | null;

  @Column('text', { array: true, nullable: true })
  ageRatingCategories: string[] | null;

  @OneToOne(() => Video, (video) => video.metadata)
  @JoinColumn({
    name: 'videoId',
    referencedColumnName: 'id',
  })
  video: Video;

  @VersionColumn()
  version: number;
}
