import { MigrationInterface, QueryRunner } from 'typeorm';

export class Migration1747604113207 implements MigrationInterface {
  name = 'Migration1747604113207';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "VideoMetadata" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP DEFAULT now(), "transcript" text NOT NULL, "autoGeneratedDescription" text, "ageRating" integer, "ageRatingExplanation" text, "ageRatingCategories" text array, "video_id" uuid, CONSTRAINT "REL_6a50216632999696db0bf861f2" UNIQUE ("video_id"), CONSTRAINT "PK_67db734088f52ed6ffea3346abf" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `ALTER TABLE "TvShow" DROP CONSTRAINT "FK_b6ac53aff4b7200e4b01ca43a9c"`,
    );
    await queryRunner.query(
      `ALTER TABLE "TvShow" ALTER COLUMN "contentId" SET NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "VideoMetadata" ADD CONSTRAINT "FK_6a50216632999696db0bf861f2a" FOREIGN KEY ("video_id") REFERENCES "Video"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "Episode" ADD CONSTRAINT "FK_3dc5f16eddbe518eff23f510ec6" FOREIGN KEY ("tvShowId") REFERENCES "TvShow"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "TvShow" ADD CONSTRAINT "FK_b6ac53aff4b7200e4b01ca43a9c" FOREIGN KEY ("contentId") REFERENCES "Content"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "TvShow" DROP CONSTRAINT "FK_b6ac53aff4b7200e4b01ca43a9c"`,
    );
    await queryRunner.query(
      `ALTER TABLE "Episode" DROP CONSTRAINT "FK_3dc5f16eddbe518eff23f510ec6"`,
    );
    await queryRunner.query(
      `ALTER TABLE "VideoMetadata" DROP CONSTRAINT "FK_6a50216632999696db0bf861f2a"`,
    );
    await queryRunner.query(
      `ALTER TABLE "TvShow" ALTER COLUMN "contentId" DROP NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "TvShow" ADD CONSTRAINT "FK_b6ac53aff4b7200e4b01ca43a9c" FOREIGN KEY ("contentId") REFERENCES "Content"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(`DROP TABLE "VideoMetadata"`);
  }
}
