import { Video } from '@contentModule/persistence/entity/video.entity';
import { Injectable } from '@nestjs/common';
import { VideoSummaryGeneratorAdapter } from '../adapter/video-summary-generator.adapter.interface';
import { AppLogger } from '@sharedModule/logger/service/app-logger.service';
import { VideoMetadataRepository } from '@contentModule/persistence/repository/video-metadata.repository';
import { VideoMetadata } from '@contentModule/persistence/entity/video-metadata.entity';

@Injectable()
export class GenerateSummaryForVideoUseCase {
  constructor(
    private readonly videoSummaryGenerator: VideoSummaryGeneratorAdapter,
    private readonly videoMetadataRepository: VideoMetadataRepository,
    private readonly logger: AppLogger,
  ) {}

  public async execute(video: Video): Promise<void> {
    const summary = await this.videoSummaryGenerator.generateSummary(video.url);
    if (!summary) {
      throw new Error(`Failed to generate summary for video ID ${video.id}`);
    }
    this.logger.log(`Generated summary for video ID ${video.id}`, {
      summary,
      videoId: video.id,
    });

    const metadata = await this.videoMetadataRepository.findOne({
      where: { video },
    });

    if (metadata) {
      metadata.autoGeneratedDescription = summary;
      await this.videoMetadataRepository.save(metadata);
      return;
    }

    const newMetadata = new VideoMetadata({
      video,
      autoGeneratedDescription: summary,
    });

    await this.videoMetadataRepository.save(newMetadata);
  }
}
